### ISSUE TITLE
Add USD to !price

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-irc-price-bot#3]
Would be very nice if the !price command could return dcr/usd.

Of the exchanges used, only poloniex gives USD info for BTC.  Could use their value along with their btc value or average the btc/dcr values then use the poloniex value (or possibly grab from elsewhere).

**Comment by jolan** [comment]
Can probably just use https://api.coinmarketcap.com/v1/ticker/decred/

It seems like it gives USD from the exchange with top volume.
